[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "tesseract"]

[phases.install]
cmds = ["python3.11 -m pip install --upgrade pip", "python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3.11 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
