[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300 --limit-max-requests 0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
maxBodySize = 104857600  # 100MB
